### ISSUE TITLE
NPE when oppening terminal starting game.

### ISSUE THREAD

**Issue by DiegoRutolo** [CyclopsMC/IntegratedTerminals-Compat#10]
```
java.lang.NullPointerException: Cannot invoke "mezz.jei.api.runtime.IJeiRuntime.getIngredientListOverlay()" because "org.cyclops.integratedterminalscompat.modcompat.jei.JEIIntegratedTerminalsConfig.jeiRuntime" is null
	at org.cyclops.integratedterminalscompat.modcompat.jei.JEIIntegratedTerminalsConfig.onTerminalStorageScreenSize(JEIIntegratedTerminalsConfig.java:115) ~[IntegratedTerminals-1.18.2-1.4.10.jar%23187!/:1.4.10] {re:classloading,pl:rei_plugin_compatibilities:B}
```

I got a NullPointer in line

https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/0349febc622892d996b54386b9c6397cf55c04f6/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/JEIIntegratedTerminalsConfig.java#L117

I oppened a terminal just after loggin into a singleplayer world, I belive the reason for the crash is JEI was not finished initializing. A simple null check at the start of the method should solve de issue.

[crash-2024-04-15_08.37.06-client.txt](https://github.com/CyclopsMC/IntegratedTerminals-Compat/files/14975118/crash-2024-04-15_08.37.06-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
