### ISSUE TITLE
JEI compat overloads client

### ISSUE THREAD

**Issue by Snonky** [CyclopsMC/IntegratedTerminals-Compat#5]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

When playing large mod packs and having a lot of items stored in the network, the JEI `transferRecipe` compat will overload the client.

#### Steps to reproduce the problem:

1. Install way too many mods
2. Get your storage full of different items
3. Press 'u' in JEI on a common item
4. The longer the recipe list the more load on the client.

Here's an example of a list with 12 pages of recipes (I pressed 'u' on planks):

![jei_recipe_list](https://user-images.githubusercontent.com/47639380/235178432-66deb4ce-a8af-4be1-bc1f-7b00a05cfcf4.jpg)

____

#### Versions:

- This mod: 1.0.0
- Minecraft: 1.19.2
- Forge: 43.2.6

____

### Proposed solution:

I'm already looking into making a PR for this and the problem lies [here](https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/68aab7c536c5ee0702e25ea09e29c1077b26f693/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/terminalstorage/TerminalStorageRecipeTransferHandler.java#L95-L98). The `transferRecipe` method is called every tick for every recipe in the JEI recipe list. Thus the cache stops working with >1 recipes in the list.

 The question is now should I implement a more sophisticated cache or just add a config option to disable recipe transfer?

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> The transferRecipe method is called every tick for every recipe in the JEI recipe list. Thus the cache stops working with >1 recipes in the list.

Aha, that's a good catch!

Probably a better caching system is needed.

Also: https://github.com/CyclopsMC/IntegratedDynamics/issues/1247

**Comment by Snonky** [comment]
I built a cache and it makes the recipe screen usable in networks with large storage:

### Before 

https://user-images.githubusercontent.com/47639380/235269260-de9e7269-6b72-4350-91ce-1b0ef5d9e7ac.mp4

### After

https://user-images.githubusercontent.com/47639380/235269280-8a6a49fd-df81-4e4f-9c61-88055f3cf296.mp4

I could make this a PR and then look into optimizing the recipe lookup itself.

**Comment by rubensworks** [comment]
@Snonky A PR with cache improvement is definitely welcome!
But it will certainly not be sufficient, but already a great step in the right direction.

I have some plans for fully resolving the performance issues, but that will require some internal changes in ID. Since the effort of this will take a while, so your workaround as temporary improvement will definitely be helpful.

**Comment by rubensworks** [comment]
This was resolved, see https://github.com/CyclopsMC/IntegratedDynamics/issues/1247 (more improvements coming in https://github.com/CyclopsMC/IntegratedTerminals-Compat/pull/8)
