### ISSUE TITLE
Removed JEI API functions in 1.19.4

### ISSUE THREAD

**Issue by Snonky** [CyclopsMC/IntegratedTerminals-Compat#7]
#### Issue type:

- :heavy_plus_sign: Feature request 
I'm not sure if this counts as a feature request 😅
____

#### Short description:

`TerminalStorageGuiHandler` uses some JEI API functions that were deprecated and have been removed in the 1.19.4 version. Specifically [`IGuiContainerHandler#getIngredientUnderMouse`](https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/68aab7c536c5ee0702e25ea09e29c1077b26f693/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/terminalstorage/TerminalStorageGuiHandler.java#L19) and [`IIngredientManager#getIngredientType`](https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/68aab7c536c5ee0702e25ea09e29c1077b26f693/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/terminalstorage/TerminalStorageGuiHandler.java#L29).

I'd be happy to bring the `TerminalStorageGuiHandler` up to speed with the JEI API if needed 👍

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Sure, feel free to look into it!

The master-1.19 branch is already using 1.19.4, but may still be using an older JEI version.

**Comment by rubensworks** [comment]
Done in #9
